name: Trigger another repo workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'hashpire',
              repo: 'web3-garden',
              workflow_id: 'update-sm.yml',
              ref: 'main'
            });
